services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: always
    ports:
      - 3000:3000
    networks:
      - cas-ru.com_network

networks:
  cas-ru.com_network:
    driver: bridge
